apiVersion: v1
data:
  default-resource.yaml: |-
    backup-target: cifs://10.42.0.3/longhorn_backups
    backup-target-credential-secret: smb-longhorn-backups-rw
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.10.0
    helm.sh/chart: longhorn-1.10.0
  name: longhorn-default-resource
  namespace: longhorn
