apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.9.1
    helm.sh/chart: longhorn-1.9.1
    name: longhorn-prometheus-servicemonitor
  name: longhorn-prometheus-servicemonitor
  namespace: longhorn
spec:
  endpoints:
    - port: manager
  namespaceSelector:
    matchNames:
      - longhorn
  selector:
    matchLabels:
      app: longhorn-manager
