apiVersion: v1
data:
  runtime-config.yaml: |
    {}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.5.7
    helm.sh/chart: loki-6.46.0
  name: loki-runtime
  namespace: monitoring
