apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/component: prometheus-operator
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 79.5.0
    chart: kube-prometheus-stack-79.5.0
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-operator
  namespace: monitoring
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app: kube-prometheus-stack-operator
    release: prometheus
  type: ClusterIP
